name: Building wheel package

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Set PATH
      run: echo "::add-path::$PWD/depot_tools"
    - name: Build Skia
      run: |
        cd skia
        python tools/git-sync-deps
        bin/gn gen out/Release --args='is_official_build=false is_debug=false extra_cflags_cc=["-frtti"]'
        ninja -C out/Release skia skia.h
        cd ..
    # TODO: Cache skia headers and binary


