name: Building wheel package

on: push

jobs:
  build-manylinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - quay.io/pypa/manylinux2010_x86_64
    container:
      image: ${{ matrix.container }}
    steps:
    - name: Install Node.js 12
      run: |
        curl -L -O https://github.com/jcheng5/node-centos6/releases/download/v12.16.1/node-v12.16.1-linux-x64.tar.gz
        tar xzf node-v12.16.1-linux-x64.tar.gz
        mv node-v12.16.1-linux-x64/* /__e/node12/
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 2.7
      run: echo "::add-path::/opt/python/cp27-cp27m/bin"
    - name: Set PATH
      run: echo "::add-path::$PWD/depot_tools"
    - name: Install gn
      env:
        CC: gcc
        CXX: g++
        AR: ar
        LDFLAGS: -lrt
      run: |
        git clone https://gn.googlesource.com/gn
        cd gn
        python build/gen.py
        ninja -C out
        cp -f out/gn ../skia/bin/gn
        cd ..
    - name: Install libfreetype2 and fontconfig
      run: |
        yum install -y freetype-devel expat-devel
        curl -L -O https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.10.93.tar.bz2
        tar xjf fontconfig-2.10.93.tar.bz2
        cd fontconfig-2.10.93
        ./configure --prefix=/usr \
                    --sysconfdir=/etc \
                    --localstatedir=/var \
                    --docdir=/usr/share/doc/fontconfig-2.10.93 \
                    --disable-docs \
                    --disable-static
        make -j2 install
        cd ..
    - name: Build Skia
      run: |
        cd skia
        python tools/git-sync-deps
        bin/gn gen out/Release --args='is_official_build=false is_debug=false extra_cflags_cc=["-frtti"]'
        ninja -C out/Release skia skia.h
        cd ..
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Set PATH
      run: echo "::add-path::$PWD/depot_tools"
    - name: Cache Third Party
      uses: actions/cache@v1
      with:
        path: skia/third_party/externals
        key: ${{ runner.os }}-third-party
    - name: Cache Skia
      uses: actions/cache@v1
      with:
        path: skia/out/Release
        key: ${{ runner.os }}-build-cache-skia
    - name: Build Skia
      run: |
        cd skia
        python tools/git-sync-deps
        bin/gn gen out/Release --args='is_official_build=false is_debug=false extra_cflags_cc=["-frtti"]'
        ninja -C out/Release skia skia.h
        cd ..
