name: Building wheel package

on: push

jobs:
  build-manylinux2010:
    if: false
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up Python 2.7
      run: echo "::add-path::/opt/python/cp27-cp27m/bin"
    - name: Set PATH
      run: echo "::add-path::$PWD/depot_tools"
    - name: Install gn
      env:
        CC: gcc
        CXX: g++
        AR: ar
        LDFLAGS: -lrt
      run: |
        git clone https://gn.googlesource.com/gn
        cd gn
        python build/gen.py
        ninja -C out
        cd ..
    - name: Install libfreetype2 and fontconfig
      run: |
        yum install -y freetype-devel expat-devel
        curl -L -O https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.10.93.tar.bz2
        tar xjf fontconfig-2.10.93.tar.bz2
        cd fontconfig-2.10.93
        ./configure --prefix=/usr \
                    --sysconfdir=/etc \
                    --localstatedir=/var \
                    --docdir=/usr/share/doc/fontconfig-2.10.93 \
                    --disable-docs \
                    --disable-static
        make -j2 install
        cd ..
    - name: Build Skia
      run: |
        cd skia
        python2 tools/git-sync-deps
        cp -f ../gn/out/gn bin/gn  # Replace gn.
        bin/gn gen out/Release --args='is_official_build=false is_debug=false extra_cflags_cc=["-frtti"] extra_ldflags=["-lrt"]'
        ninja -C out/Release skia skia.h
        cd ..
  build-manylinux2014:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - cp35-cp35m
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set PATH
      run: echo "::add-path::$PWD/depot_tools"
    - uses: actions/cache@v1
      with:
        path: skia/out/Release
        key: manylinux2014-skia-out
    - name: Build Skia
      run: |
        if [ ! -d "skia/out/Release" ]; then
          yum install -y fontconfig-devel
          cd skia
          python tools/git-sync-deps
          bin/gn gen out/Release --args='is_official_build=false is_debug=false extra_cflags_cc=["-frtti"] extra_ldflags=["-lrt"]'
          ninja -C out/Release skia skia.h
          cd ..
        fi
    - name: Set up Python
      run: echo "::add-path::/opt/python/${{ matrix.python-version }}/bin"
    - name: Build python binding
      run: |
        python -m pip install -U pip
        python -m pip install pybind11 wheel
        python setup.py bdist_wheel
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
        python-version: [3.5]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Set PATH
      run: echo "::add-path::$PWD/depot_tools"
    - uses: actions/cache@v1
      with:
        path: skia/out/Release
        key: ${{ runner.os }}-skia-out
    - name: Build Skia (macOS)
      run: |
        if [ ! -d "skia/out/Release" ]; then
          cd skia
          python tools/git-sync-deps
          bin/gn gen out/Release --args='is_official_build=false is_debug=false extra_cflags_cc=["-frtti"]'
          ninja -C out/Release skia skia.h
          cd ..
        fi
      if: runner.os == 'macOS'
    - name: Build Skia (Windows)
      shell: bash
      run: |
        if [ ! -d "skia/out/Release" ]; then
          cd skia
          python tools/git-sync-deps
          bin/gn gen out/Release --args='is_official_build=false is_debug=false'
          ninja -C out/Release skia skia.h
          cd ..
        fi
      if: runner.os == 'Windows'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build python binding
      run: |
        python -m pip install -U pip
        python -m pip install pybind11 wheel
        python setup.py bdist_wheel
